#!/usr/bin/env bash
#
# SPDX-License-Identifier: GPL-2.0
#
# Copyright (c) 2013-2023 Igor Pecovnik, igor@armbian.com
#
# This file is a part of the Armbian Build Framework
# https://github.com/armbian/build/

# prepare_partitions
#
# creates image file, partitions and fs
# and mounts it to local dir
# FS-dependent stuff (boot and root fs partition types) happens here
#
# LOGGING: this is run under the log manager. so just redirect unwanted stderr to stdout, and it goes to log.
# this is under the logging manager. so just log to stdout (no redirections), and redirect stderr to stdout unless you want it on screen.
function prepare_partitions() {
	display_alert "Preparing image file for rootfs" "$BOARD $RELEASE" "info"

	# possible partition combinations
	# /boot: none, ext4, ext2, fat (BOOTFS_TYPE)
	# root: ext4, btrfs, f2fs, nilfs2, nfs (ROOTFS_TYPE)

	# declare makes local variables by default if used inside a function
	# NOTE: mountopts string should always start with comma if not empty

	# array copying in old bash versions is tricky, so having filesystems as arrays
	# with attributes as keys is not a good idea
	declare -A parttype mkopts mkopts_label mkfs mountopts

	parttype[ext4]=ext4
	parttype[ext2]=ext2
	parttype[fat]=fat16
	parttype[f2fs]=ext4 # not a copy-paste error
	parttype[btrfs]=btrfs
	parttype[nilfs2]=nilfs2
	parttype[xfs]=xfs
	# parttype[nfs] is empty

	mkopts[ext4]="-q -m 2" # for a long time we had '-O ^64bit,^metadata_csum' here
	# mkopts[fat] is empty
	mkopts[ext2]=''
	# mkopts[f2fs] is empty
	mkopts[btrfs]='-m dup'
	# mkopts[nilfs2] is empty
	# mkopts[xfs] is empty
	# mkopts[nfs] is empty

	mkopts_label[ext4]='-L '
	mkopts_label[ext2]='-L '
	mkopts_label[fat]='-n '
	mkopts_label[f2fs]='-l '
	mkopts_label[btrfs]='-L '
	mkopts_label[nilfs2]='-L '
	mkopts_label[xfs]='-L '
	# mkopts_label[nfs] is empty

	mkfs[ext4]=ext4
	mkfs[ext2]=ext2
	mkfs[fat]=vfat
	mkfs[f2fs]=f2fs
	mkfs[btrfs]=btrfs
	mkfs[nilfs2]=nilfs2
	mkfs[xfs]=xfs
	# mkfs[nfs] is empty

	mountopts[ext4]=',commit=600,errors=remount-ro'
	# mountopts[ext2] is empty
	# mountopts[fat] is empty
	# mountopts[f2fs] is empty
	mountopts[btrfs]=',commit=600'
	# mountopts[nilfs2] is empty
	# mountopts[xfs] is empty
	# mountopts[nfs] is empty

	# default BOOTSIZE to use if not specified
	DEFAULT_BOOTSIZE=256 # MiB
	# size of UEFI partition. 0 for no UEFI. Don't mix UEFISIZE>0 and BOOTSIZE>0
	UEFISIZE=${UEFISIZE:-0}
	BIOSSIZE=${BIOSSIZE:-0}
	UEFI_MOUNT_POINT="${UEFI_MOUNT_POINT:-/boot/efi}"

	# Create the data mount point name globals
	data_mount_name="var"
	data_mount_point="${data_mount_point:-/$data_mount_name}"
	declare -g -r DATA_MOUNT_NAME="${data_mount_name}"
	declare -g -r DATA_MOUNT_POINT="${data_mount_point}"

	bdata_mount_name="bdata"
	bdata_mount_point="${bdata_mount_point:-/$bdata_mount_name}"
	bdatafs_type=fat
	declare -g -r BDATA_MOUNT_NAME="${bdata_mount_name}"
	declare -g -r BDATA_MOUNT_POINT="${bdata_mount_point}"
	declare -g -r BDATA_FS_TYPE="${bdatafs_type}"

	# Create the partition labels
	UEFI_FS_LABEL="${UEFI_FS_LABEL:-armbi_efi}"
	ROOTA_FS_LABEL="${ROOTA_FS_LABEL:-armbi_roota}"
	# Create the data FS label
	DATA_FS_LABEL="${DATA_FS_LABEL:-armbi_$data_mount_name}"
	BDATA_FS_LABEL="${BDATA_FS_LABEL:-armbi_$bdata_mount_name}"
	# Create the boot FS label
	BOOT_FS_LABEL="${BOOT_FS_LABEL:-armbi_boot}"

	# Log the rootFS labels and the data label
	display_alert "*** ROOTFS labels" "root label: ${ROOTA_FS_LABEL}" "info"
	display_alert "*** DATAFS label " "data label: ${DATA_FS_LABEL}" "info"
	display_alert "*** BDATAFS label" "bdata label: ${BDATA_FS_LABEL}" "info"

	call_extension_method "pre_prepare_partitions" "prepare_partitions_custom" <<- 'PRE_PREPARE_PARTITIONS'
		*allow custom options for mkfs*
		Good time to change stuff like mkfs opts, types etc.
	PRE_PREPARE_PARTITIONS

	# stage: determine partition configuration
	local next=1
	# Check if we need UEFI partition
	if [[ $UEFISIZE -gt 0 ]]; then
		# Check if we need BIOS partition
		[[ $BIOSSIZE -gt 0 ]] && local biospart=$((next++))
		local uefipart=$((next++))
	fi
	# Check if we need boot partition
	if [[ -n $BOOTFS_TYPE || $ROOTFS_TYPE != ext4 || $CRYPTROOT_ENABLE == yes ]]; then
		local bootpart=$((next++))
		local bootfs=${BOOTFS_TYPE:-ext4}
		[[ -z $BOOTSIZE || $BOOTSIZE -le 8 ]] && BOOTSIZE=${DEFAULT_BOOTSIZE}
	else
		BOOTSIZE=0
	fi
	# Check if we need root partition
	# Add the rootB partition
	[[ $ROOTFS_TYPE != nfs ]] &&
		rootapart=$((next++)) &&
		datapart=$((next++)) &&
		bdatapart=$((next++))

	# Log the partition indices
	display_alert "calculated rootapart and datapart" "rootapart: ${rootapart}, datapart: ${datapart}, bdatapart: ${bdatapart}" "info"

	# stage: calculate rootfs size
	declare -g -i rootafs_size
	# Declare the global variables for rootfsb and datafs
	declare -g -i datafs_size
	declare -g -i bdatafs_size

	# Pre-computed by looking at the rootfs files generated by the build
	rootafs_size=10000 # MiB
	# Set the data partition size - used in the initial image creation - data can grow to the extent of the storage device
	datafs_size=3000 # MiB
	bdatafs_size=512 # MiB

	# Log the root partition sizes
	display_alert "Current fs sizes" "root: $rootafs_size MiB, data: $datafs_size MiB, bdata: $bdatafs_size" "info"

	call_extension_method "prepare_image_size" "config_prepare_image_size" <<- 'PREPARE_IMAGE_SIZE'
		*allow dynamically determining the size based on the $rootafs_size*
		Called after `${rootafs_size}` is known, but before `${FIXED_IMAGE_SIZE}` is taken into account.
		A good spot to determine `FIXED_IMAGE_SIZE` based on `rootafs_size`.
		UEFISIZE can be set to 0 for no UEFI partition, or to a size in MiB to include one.
		Last chance to set `USE_HOOK_FOR_PARTITION`=yes and then implement create_partition_table hook_point.
	PREPARE_IMAGE_SIZE

	local sdsize
	local totalsize
	if [[ -n $FIXED_IMAGE_SIZE && $FIXED_IMAGE_SIZE =~ ^[0-9]+$ ]]; then
		display_alert "Using user-defined image size" "$FIXED_IMAGE_SIZE MiB" "info"
		sdsize=$FIXED_IMAGE_SIZE
		# basic sanity check
		# Compute the approximate total size of the entire OS if a fixed image size is requested
		totalsize=$(($rootafs_size + $datafs_size + $bdatafs_size))
		if [[ $ROOTFS_TYPE != nfs && $sdsize -lt $totalsize ]]; then
			exit_with_error "User defined image size is too small" "$sdsize <= $totalsize"
		fi
	else
		# Otherwise, assume the data partition will consume whatever is left of storage after the boot, rootA, and rootB partitions
		local imagesize=$(($rootafs_size + $bdatafs_size + $OFFSET + $BOOTSIZE + $UEFISIZE + $EXTRA_ROOTFS_MIB_SIZE)) # MiB
		# Hardcoded overhead +25% is needed for desktop images,
		# for CLI it could be lower. Align the size up to 4MiB
		if [[ $BUILD_DESKTOP == yes ]]; then
			sdsize=$(bc -l <<< "scale=0; ((($imagesize * 1.35) / 1 + 0) / 4 + 1) * 4")
		else
			sdsize=$(bc -l <<< "scale=0; ((($imagesize * 1.30) / 1 + 0) / 4 + 1) * 4")
		fi
	fi

	# stage: create blank image # GJL
	display_alert "Creating blank image for rootfsA and data and bdata" "truncate: $sdsize MiB" "info"
	run_host_command_logged truncate "--size=${sdsize}M" "${SDCARD}".raw # please provide EVIDENCE of problems with this; using dd is very slow
	wait_for_disk_sync "after truncate SDCARD.raw"

	# stage: calculate boot partition size
	local bootstart=$(($OFFSET * 2048))
	local roota_start=$(($bootstart + ($BOOTSIZE * 2048) + ($UEFISIZE * 2048)))
	local bdata_start=$(($roota_start + $rootafs_size))
	# Compute the data partition start point
	local data_start=$(($bdata_start + $bdatafs_size))
	# Compute the boot partition end point
	local bootend=$(($roota_start - 1))

	# stage: create dual root plus data partition table
	display_alert "Creating partitions" "${bootfs:+/boot: $bootfs } root: $ROOTFS_TYPE, ${DATA_MOUNT_POINT}: $ROOTFS_TYPE, ${BDATA_MOUNT_POINT}: $BDATA_FS_TYPE" "info"
	if [[ "${USE_HOOK_FOR_PARTITION}" == "yes" ]]; then
		{ [[ "$IMAGE_PARTITION_TABLE" == "msdos" ]] && echo "label: dos" || echo "label: $IMAGE_PARTITION_TABLE"; } |
			run_host_command_logged sfdisk "${SDCARD}".raw || exit_with_error "Create partition table fail"

		call_extension_method "create_partition_table" <<- 'CREATE_PARTITION_TABLE'
			*only called when USE_HOOK_FOR_PARTITION=yes to create the complete partition table*
			Finally, we can get our own partition table. You have to partition ${SDCARD}.raw
			yourself. Good luck.
		CREATE_PARTITION_TABLE
	else
		# Create a script in a bracket shell, then pipe it to fdisk.
		{
			[[ "$IMAGE_PARTITION_TABLE" == "msdos" ]] && echo "label: dos" || echo "label: $IMAGE_PARTITION_TABLE"

			local next=$OFFSET
			if [[ -n "$biospart" ]]; then
				# gpt: BIOS boot
				local type="21686148-6449-6E6F-744E-656564454649"
				echo "$biospart : name=\"bios\", start=${next}MiB, size=${BIOSSIZE}MiB, type=${type}"
				local next=$(($next + $BIOSSIZE))
			fi
			if [[ -n "$uefipart" ]]; then
				# dos: EFI (FAT-12/16/32)
				# gpt: EFI System
				[[ "$IMAGE_PARTITION_TABLE" != "gpt" ]] && local type="ef" || local type="C12A7328-F81F-11D2-BA4B-00A0C93EC93B"
				echo "$uefipart : name=\"efi\", start=${next}MiB, size=${UEFISIZE}MiB, type=${type}"
				local next=$(($next + $UEFISIZE))
			fi
			if [[ -n "$bootpart" ]]; then
				# Linux extended boot
				[[ "$IMAGE_PARTITION_TABLE" != "gpt" ]] && local type="ea" || local type="BC13C2FF-59E6-4262-A352-B275FD6F7172"
				if [[ -n "$rootpart" ]]; then
					echo "$bootpart : name=\"bootfs\", start=${next}MiB, size=${BOOTSIZE}MiB, type=${type}"
					local next=$(($next + $BOOTSIZE))
				else
					# no `size` argument mean "as much as possible"
					echo "$bootpart : name=\"bootfs\", start=${next}MiB, type=${type}"
				fi
			fi
			if [[ -n "$rootapart" ]]; then
				# dos: Linux
				# gpt: Linux filesystem
				[[ "$IMAGE_PARTITION_TABLE" != "gpt" ]] && local type="83" || local type="0FC63DAF-8483-4772-8E79-3D69D8477DE4"

				echo "$rootapart : name=\"rootfs\", start=${next}MiB, size=${rootafs_size}MiB type=${type}"
				local next=$(($next + $rootafs_size))
			fi
			if [[ -n "$bdatapart" ]]; then
				# dos: Type 'c' is LBA FAT
				# gpt: Linux data partition
				[[ "$IMAGE_PARTITION_TABLE" != "gpt" ]] && local type="c" || local type="0FC63DAF-8483-4772-8E79-3D69D8477DE4"

				echo "$bdatapart : name=\"bdatafs\", start=${next}MiB, size=${bdatafs_size}MiB type=${type}"
				local next=$(($next + $bdatafs_size))
			fi
			if [[ -n "$datapart" ]]; then
				# dos: Linux
				# gpt: Linux filesystem
				[[ "$IMAGE_PARTITION_TABLE" != "gpt" ]] && local type="83" || local type="0FC63DAF-8483-4772-8E79-3D69D8477DE4"
				# no `size` argument mean "as much as possible"
				echo "$datapart : name=\"datafs\", start=${next}MiB, type=${type}"
			fi
		} |
			run_host_command_logged sfdisk "${SDCARD}".raw || exit_with_error "Partition fail."
	fi

	call_extension_method "post_create_partitions" <<- 'POST_CREATE_PARTITIONS'
		*called after all partitions are created, but not yet formatted*
	POST_CREATE_PARTITIONS

	# stage: mount image
	# lock access to loop devices
	exec {FD}> /var/lock/armbian-debootstrap-losetup
	flock -x $FD

	declare -g LOOP
	# Taken from https://github.com/armbian/build/pull/6345
	# replace losetup --find with own function and do 10 cycles
	# losetup always return 1st free loop device and in parallel build,
	# it often happens that same is found which resoults in:
	# "failed to set up loop device: Device or resource busy"
	# If we seek random way, chanches of allocating the same are significantly smaller.
	MAX_LOOP_CYCLES=10
	if [[ "trixie lunar mantic" == *"${host_release}"* ]]; then
		# On later Ubuntu releases, snapd consumes a large number of loop devices
		# To get around this, increase the number of search cycles and also
		# ensure that GRUB_CMDLINE_LINUX_DEFAULT has a 'max_loop=64' entry in /etc/default/grub on native Linux host
		# Note: If you edit /etc/default/grub, be sure to run update-grub afterwards and restart the machine
		MAX_LOOP_CYCLES=25
	fi

	FIND_LOOP_CYCLES=1
	while : ; do
		LOOP=$(find /dev/loop* | grep -Po "(\/dev\/loop\d|\/dev\/loop\d\d)$" | sort -R | head -1)
		LOOP_COMPARE=$(losetup -l --noheadings --raw --output=NAME | grep $LOOP || true)
		[[ -z $LOOP_COMPARE ]] && break
		[[ $FIND_LOOP_CYCLES -gt 10 ]] && exit_with_error "Unable to find free loop device"
		FIND_LOOP_CYCLES=$(( FIND_LOOP_CYCLES + 1 ))
	done
	display_alert "Allocated loop device" "LOOP=${LOOP} in cycle $FIND_LOOP_CYCLES"

	CHECK_LOOP_FOR_SIZE="no" check_loop_device "$LOOP" # initially loop is zero sized, ignore it.

	# Taken from https://github.com/armbian/build/pull/6334
    #--partscan is using to force the kernel for scaning partition table in preventing of partprobe errors
	run_host_command_logged losetup --partscan "${LOOP}" "${SDCARD}".raw

	# loop device was grabbed here, unlock
	flock -u $FD

	display_alert "Running partprobe" "${LOOP}" "debug"
	run_host_command_logged partprobe "${LOOP}"

	display_alert "Checking again after partprobe" "${LOOP}" "debug"
	check_loop_device "${LOOP}" # check again, now it has to have a size! otherwise wait.

	# stage: create fs, mount partitions, create fstab
	SDCARD_FSTAB="${SDCARD}/etc/fstab"
	rm -f "${SDCARD_FSTAB}"

	declare roota_part_uuid="uninitialized"
	declare rootb_part_uuid="uninitialized"
	declare data_part_uuid="uninitialized"
	declare bdata_part_uuid="uninitialized"

	# Create the data partition
	if [[ -n $datapart ]]; then
		local datadevice="${LOOP}p${datapart}"

		check_loop_device "$datadevice"
		display_alert "Creating datafs" "$ROOTFS_TYPE on $datadevice" "info"
		run_host_command_logged mkfs.${mkfs[$ROOTFS_TYPE]} ${mkopts[$ROOTFS_TYPE]} ${mkopts_label[$ROOTFS_TYPE]:+${mkopts_label[$ROOTFS_TYPE]}"$DATA_FS_LABEL"} "${datadevice}"
		[[ $ROOTFS_TYPE == ext4 ]] && run_host_command_logged tune2fs -o journal_data_writeback "$datadevice"
		if [[ $ROOTFS_TYPE == btrfs && $BTRFS_COMPRESSION != none ]]; then
			local fscreateopt="-o compress-force=${BTRFS_COMPRESSION}"
		fi
		wait_for_disk_sync "after mkfs" # force writes to be really flushed

		# store in readonly global for usage in later hooks
		data_part_uuid="$(blkid -s UUID -o value ${LOOP}p${datapart})"
		declare -g -r DATA_PART_UUID="${data_part_uuid}"

		mkdir -p "${MOUNT}${DATA_MOUNT_POINT}"
		display_alert "Mounting datafs" "$datadevice (UUID=${DATA_PART_UUID})"
		run_host_command_logged mount ${fscreateopt} $datadevice "${MOUNT}${DATA_MOUNT_POINT}"

		# create fstab (and crypttab) entry
		local datafs
		datafs="UUID=$(blkid -s UUID -o value $datadevice)"
		# Create the fstab entry and leave it commented out for the /var partition
		echo "# $datafs ${DATA_MOUNT_POINT} ${mkfs[$ROOTFS_TYPE]} defaults,noatime${mountopts[$ROOTFS_TYPE]} 0 2" >> "${SDCARD_FSTAB}"
	else
		# update_initramfs will fail if /lib/modules/ doesn't exist
		mount --bind --make-private $SDCARD "${MOUNT}${DATA_MOUNT_POINT}"
		echo "/dev/nfs ${DATA_MOUNT_POINT} nfs defaults 0 0" >> "${SDCARD_FSTAB}"
	fi

	if [[ -n $bdatapart ]]; then
		local bdatadevice="${LOOP}p${bdatapart}"

		check_loop_device "$bdatadevice"
		display_alert "Creating bdatafs" "FAT32 on $bdatadevice" "info"
		#run_host_command_logged mkfs.${mkfs[$BDATA_FS_TYPE]} ${mkopts[$BDATA_FS_TYPE]} ${mkopts_label[$BDATA_FS_TYPE]:+${mkopts_label[$BDATA_FS_TYPE]}"$BDATA_FS_LABEL"} "${bdatadevice}"
		run_host_command_logged mkfs.fat -F32 -n "${BDATA_FS_LABEL^^}" "${bdatadevice}" 2>&1 # "^^" makes variable UPPERCASE, required for FAT32.

		# store in readonly global for usage in later hooks
		bdata_part_uuid="$(blkid -s UUID -o value ${LOOP}p${bdatapart})"
		declare -g -r BDATA_PART_UUID="${bdata_part_uuid}"

		mkdir -p "${MOUNT}${BDATA_MOUNT_POINT}"
		display_alert "Mounting bdatafs" "$bdatadevice (UUID=${BDATA_PART_UUID})"
		run_host_command_logged mount $bdatadevice "${MOUNT}${BDATA_MOUNT_POINT}"

		# create fstab (and crypttab) entry
		local bdatafs
		bdatafs="UUID=$(blkid -s UUID -o value $bdatadevice)"
		# Ensure FSCK does not run on the bdatafs as it is a FAT32 partition with no journaling
		echo "$bdatafs ${BDATA_MOUNT_POINT} vfat defaults,auto,users,rw,noexec 0 2" >> "${SDCARD_FSTAB}"
	else
		# update_initramfs will fail if /lib/modules/ doesn't exist
		mount --bind --make-private $SDCARD "${MOUNT}${BDATA_MOUNT_POINT}"
		echo "/dev/nfs ${BDATA_MOUNT_POINT} nfs defaults 0 0" >> "${SDCARD_FSTAB}"
	fi

	# Create the primary root partition
	if [[ -n $rootapart ]]; then
		local rootadevice="${LOOP}p${rootapart}"

		check_loop_device "$rootadevice"
		display_alert "Creating rootfs A" "$ROOTFS_TYPE on $rootadevice" "info"
		run_host_command_logged mkfs.${mkfs[$ROOTFS_TYPE]} ${mkopts[$ROOTFS_TYPE]} ${mkopts_label[$ROOTFS_TYPE]:+${mkopts_label[$ROOTFS_TYPE]}"$ROOTA_FS_LABEL"} "${rootadevice}"
		[[ $ROOTFS_TYPE == ext4 ]] && run_host_command_logged tune2fs -o journal_data_writeback "$rootadevice"
		if [[ $ROOTFS_TYPE == btrfs && $BTRFS_COMPRESSION != none ]]; then
			local fscreateopt="-o compress-force=${BTRFS_COMPRESSION}"
		fi
		wait_for_disk_sync "after mkfs" # force writes to be really flushed

		# store in readonly global for usage in later hooks
		roota_part_uuid="$(blkid -s UUID -o value ${LOOP}p${rootapart})"
		declare -g -r ROOTA_PART_UUID="${roota_part_uuid}"

		display_alert "Mounting rootfsA" "$rootadevice (UUID=${ROOTA_PART_UUID})"
		run_host_command_logged mount ${fscreateopt} $rootadevice $MOUNT/

		# create fstab (and crypttab) entry
		local rootafs
		rootafs="UUID=$(blkid -s UUID -o value $rootadevice)"
		echo "$rootafs / ${mkfs[$ROOTFS_TYPE]} defaults,noatime${mountopts[$ROOTFS_TYPE]} 0 1" >> "${SDCARD_FSTAB}"
	else
		# update_initramfs will fail if /lib/modules/ doesn't exist
		mount --bind --make-private $SDCARD $MOUNT/
		echo "/dev/nfs / nfs defaults 0 0" >> "${SDCARD_FSTAB}"
	fi

	if [[ -n $bootpart ]]; then
		display_alert "Creating /boot" "$bootfs on ${LOOP}p${bootpart}" "info"
		check_loop_device "${LOOP}p${bootpart}"
		run_host_command_logged mkfs.${mkfs[$bootfs]} ${mkopts[$bootfs]} ${mkopts_label[$bootfs]:+${mkopts_label[$bootfs]}"$BOOT_FS_LABEL"} ${LOOP}p${bootpart}
		mkdir -p $MOUNT/boot/
		run_host_command_logged mount ${LOOP}p${bootpart} $MOUNT/boot/
		local bootfsid
		bootfsid="UUID=$(blkid -s UUID -o value ${LOOP}p${bootpart})"
		echo "$bootfsid /boot ${mkfs[$bootfs]} defaults${mountopts[$bootfs]} 0 2" >> "${SDCARD_FSTAB}"
	fi
	if [[ -n $uefipart ]]; then
		display_alert "Creating EFI partition" "FAT32 ${UEFI_MOUNT_POINT} on ${LOOP}p${uefipart} label ${UEFI_FS_LABEL}" "info"
		check_loop_device "${LOOP}p${uefipart}"
		run_host_command_logged mkfs.fat -F32 -n "${UEFI_FS_LABEL^^}" ${LOOP}p${uefipart} 2>&1 # "^^" makes variable UPPERCASE, required for FAT32.
		mkdir -p "${MOUNT}${UEFI_MOUNT_POINT}"
		run_host_command_logged mount ${LOOP}p${uefipart} "${MOUNT}${UEFI_MOUNT_POINT}"
		local efifsid="UUID=$(blkid -s UUID -o value ${LOOP}p${uefipart})"
		echo "$efifsid ${UEFI_MOUNT_POINT} vfat defaults 0 2" >> "${SDCARD_FSTAB}"
	fi

	display_alert "Writing /tmp as tmpfs in chroot fstab" "${SDCARD_FSTAB}" "info"
	echo "tmpfs /tmp tmpfs defaults,nosuid 0 0" >> "${SDCARD_FSTAB}"

	call_extension_method "format_partitions" <<- 'FORMAT_PARTITIONS'
		*if you created your own partitions, this would be a good time to format them*
		The loop device is mounted, so ${LOOP}p1 is it's first partition etc.
	FORMAT_PARTITIONS

	# stage: adjust boot script or boot environment
	ARMBIAN_ENV="${SDCARD}/boot/armbianEnv.txt"
	if [[ -f "${ARMBIAN_ENV}" ]]; then
		display_alert "Found armbianEnv.txt" "${ARMBIAN_ENV}; updating rootdev and rootfstype" "info"
		echo "rootdev=$rootafs" >> "${ARMBIAN_ENV}"
		echo "rootfstype=$ROOTFS_TYPE" >> "${ARMBIAN_ENV}"
		echo "bdatadev=$bdatafs" >> "${ARMBIAN_ENV}"
		echo "bdatafstype=vfat" >> "${ARMBIAN_ENV}"
	elif [[ $rootapart != 1 ]] && [[ $SRC_EXTLINUX != yes ]]; then
		display_alert "Did not find armbianEnv.txt" "Adding rootfstype entries to ${ARMBIAN_ENV}" "info"
		echo "rootfstype=$ROOTFS_TYPE" >> "${ARMBIAN_ENV}"
	elif [[ $rootapart != 1 && $SRC_EXTLINUX != yes && -f "${SDCARD}/boot/${bootscript_dst}" ]]; then
		display_alert "Did not find armbianEnv.txt - found ${bootscript_dst}" "Updating ${SDCARD}/boot/${bootscript_dst}" "info"
		local bootscript_dst=${BOOTSCRIPT##*:}
		sed -i 's/mmcblk0p1/mmcblk0p2/' "${SDCARD}/boot/${bootscript_dst}"
		sed -i -e "s/rootfstype=ext4/rootfstype=$ROOTFS_TYPE/" \
			-e "s/rootfstype \"ext4\"/rootfstype \"$ROOTFS_TYPE\"/" "${SDCARD}/boot/${bootscript_dst}"
	fi

	# if we have boot.ini = remove armbianEnv.txt and add UUID there if enabled
	if [[ -f $SDCARD/boot/boot.ini ]]; then
		display_alert "Found boot.ini" "${SDCARD}/boot/boot.ini" "info"
		sed -i -e "s/rootfstype \"ext4\"/rootfstype \"$ROOTFS_TYPE\"/" $SDCARD/boot/boot.ini
		sed -i 's/^setenv rootdev .*/setenv rootdev "'$rootafs'"/' $SDCARD/boot/boot.ini
		if [[ $LINUXFAMILY != meson64 ]]; then # @TODO: why only for meson64?
			display_alert "Removing armbianEnv.txt" "boot.ini was found - removing armbianEnv.txt" "info"
			[[ -f $SDCARD/boot/armbianEnv.txt ]] &&
			run_host_command_logged rm -v "${ARMBIAN_ENV}"
		fi
	fi

	# if we have a headless device, set console to DEFAULT_CONSOLE
	if [[ -n $DEFAULT_CONSOLE && -f "${ARMBIAN_ENV}" ]]; then
		display_alert "Setting console" "Setting console in ${ARMBIAN_ENV}" "info"
		if grep -lq "^console=" "${ARMBIAN_ENV}"; then
			sed -i "s/^console=.*/console=$DEFAULT_CONSOLE/" "${ARMBIAN_ENV}"
		else
			echo "console=$DEFAULT_CONSOLE" >> "${ARMBIAN_ENV}"
		fi
	fi

	# recompile .cmd to .scr if boot.cmd exists
	if [[ -f "${SDCARD}/boot/boot.cmd" ]]; then
		if [ -z ${BOOTSCRIPT_OUTPUT} ]; then
			BOOTSCRIPT_OUTPUT=boot.scr
		fi
		case ${LINUXFAMILY} in
			x86)
				:
				display_alert "Compiling boot.scr" "boot/${BOOTSCRIPT_OUTPUT} x86" "debug"
				run_host_command_logged cat "${SDCARD}/boot/boot.cmd"
				run_host_command_logged mkimage -T script -C none -n "'Boot script'" -d "${SDCARD}/boot/boot.cmd" "${SDCARD}/boot/${BOOTSCRIPT_OUTPUT}"
				;;
			*)
				display_alert "Compiling boot.scr" "boot/${BOOTSCRIPT_OUTPUT} ARM" "info"
				run_host_command_logged mkimage -C none -A arm -T script -d "${SDCARD}/boot/boot.cmd" "${SDCARD}/boot/${BOOTSCRIPT_OUTPUT}"
				;;
		esac
	fi

	# complement extlinux config if it exists; remove armbianEnv in this case.
	if [[ -f $SDCARD/boot/extlinux/extlinux.conf ]]; then
		display_alert "Found extlinux.conf" "Creating extlinux.conf file" "info"
		echo "  append root=$rootafs $SRC_CMDLINE $MAIN_CMDLINE" >> $SDCARD/boot/extlinux/extlinux.conf
		display_alert "extlinux.conf exists" "removing armbianEnv.txt" "info"
		[[ -f $SDCARD/boot/armbianEnv.txt ]] &&
		run_host_command_logged rm -v "${ARMBIAN_ENV}"
	fi

	if [[ $SRC_EXTLINUX != yes && -f "${ARMBIAN_ENV}" ]]; then
		call_extension_method "image_specific_armbian_env_ready" <<- 'IMAGE_SPECIFIC_ARMBIAN_ENV_READY'
			*during image build, armbianEnv.txt is ready for image-specific customization (not in BSP)*
			You can write to `"${SDCARD}/boot/armbianEnv.txt"` here, it is guaranteed to exist.
		IMAGE_SPECIFIC_ARMBIAN_ENV_READY
	fi

	return 0 # there is a shortcircuit above! very tricky btw!
}
